# Generated by Django 4.1.2 on 2022-10-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
    ]
